export const STRINGS = {
  appTitle: "Food Donation Management",
  routes: [
    ["admin-workspace", "Admin Workspace"],
    ["inventory-staff-ui", "Inventory Allocation UI"],
    ["dashboard", "Dashboard"],
    ["donors", "Donors"],
    ["products", "Products"],
    ["lots", "Lots"],
    ["zones", "Zones"],
    ["inventory", "Inventory"],
    ["beneficiaries", "Beneficiaries"],
    ["orders", "Orders"],
    ["picking", "Picking"],
    ["reports", "Reports"],
    ["beneficiary-register", "Beneficiary Register"],
    ["beneficiary-order", "Beneficiary Order"],
    ["donor-register", "Donor Register"],
    ["donor-donation", "Make Donation"],
  ],
  errors: {
    network: "Network issue. Please try again.",
    validation: "Please fix form errors and retry.",
  },
};
