export const STRINGS = {
  appTitle: "Food Donation Management",
  routes: [
    ["admin-landing", "Admin Landing"],
    ["inventory-landing", "Inventory Landing"],
    ["beneficiary-landing", "Beneficiary Landing"],
    ["donor-landing", "Donor Landing"],
    ["admin-workspace", "Admin Workspace"],
    ["inventory-staff-ui", "Inventory Allocation UI"],
    ["dashboard", "Dashboard"],
    ["donors", "Donors"],
    ["products", "Products"],
    ["lots", "Lots"],
    ["storage", "Storage"],
    ["orders-picking", "Orders & Picking"],
    ["beneficiaries", "Beneficiaries"],
    ["reports", "Reports"],
    ["beneficiary-register", "Beneficiary Register"],
    ["beneficiary-order", "Beneficiary Order"],
    ["beneficiary-delivery-status", "Delivery Status"],
    ["beneficiary-order-submitted", "Order Submitted"],
    ["donor-register", "Donor Register"],
    ["donor-donation", "Make Donation"],
  ],
  errors: {
    network: "Network issue. Please try again.",
    validation: "Please fix form errors and retry.",
  },
};
